name: Compilar Executavel Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias e PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install flask pandas openpyxl python-dotenv google-genai pyinstaller

      - name: Gerar Executavel Windows (.exe)
        run: |
          pyinstaller --noconfirm --onedir --add-data "templates;templates" --add-data "poi_store.db;." --collect-all google.genai --collect-all dotenv --hidden-import=dotenv --name "Automacao_Relatorio_Rastreio" app.py

      - name: Disponibilizar arquivo para Download
        uses: actions/upload-artifact@v4
        with:
          name: Automacao_Relatorio_Rastreio_Windows
          path: dist/Automacao_Relatorio_Rastreio/